version: '3.8'

services:
  mongo:
    image: kaveri007/node-app:mongo-v1.0
    container_name: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "27017:27017"
    networks:
       - app_network

  mongo-express:
    image: kaveri007/node-app:mongo-express-v1.0
    container_name: mongo-express
    environment:
      - ME_CONFIG_MONGODB_SERVER=${ME_CONFIG_MONGODB_SERVER}
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${ME_CONFIG_MONGODB_ADMINUSERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${ME_CONFIG_MONGODB_ADMINPASSWORD}
      - ME_CONFIG_MONGODB_URL=${ME_CONFIG_MONGODB_URL}
    ports:
      - "8081:8081"
    networks:
       - app_network

  app-server:
    image: kaveri007/node-app:node-app-v1.0
    container_name: app-server
    environment:
      - MONGO_URL=${MONGO_URL}  # Use the secret for MongoDB URL
    ports:
      - "5050:5050"
    depends_on:
      - mongo

networks:
  app_network:
     driver: bridge

